version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: bea_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  superset:
    image: apache/superset:latest
    container_name: bea_superset
    restart: unless-stopped
    environment:
      SUPERSET_SECRET_KEY: "superset_secret"
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_DATABASE_URI: "postgresql+psycopg2://superset:superset@postgres:5432/superset"
    volumes:
      - ./superset:/app/superset_home
      - ./superset/dashboards:/app/superset_home/dashboards  # mount dashboards folder
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    command:
      [
        "sh",
        "-c",
        "
        superset db upgrade &&
        superset init &&
        # Import dashboards if JSON exists
        if [ -f /app/superset_home/dashboards/dashboards.json ]; then
          echo '📥 Importing dashboards...';
          superset import-dashboards -p /app/superset_home/dashboards/dashboards.json;
        fi &&
        gunicorn -w 4 -k gevent --timeout 120 -b 0.0.0.0:8088 'superset.app:create_app()'
        "
      ]

  dbt:
    image: fishtownanalytics/dbt:1.6.0
    container_name: bea_dbt
    restart: unless-stopped
    working_dir: /usr/app
    volumes:
      - ./dbt_project:/usr/app
    environment:
      DBT_PROFILES_DIR: /usr/app
      DBT_USER: superset
      DBT_PASS: superset
      DBT_HOST: postgres
      DBT_PORT: 5432
      DBT_DB: superset
    depends_on:
      - postgres

volumes:
  postgres_data:
