superset_dbt_bea:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost   # Change from 'postgres' to 'localhost'
      user: superset
      password: superset
      port: 5432
      dbname: superset
      schema: public
